### ISSUE TITLE
Installation instructions for Linux?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [sr33/ares#8]
Hello! I don't think your install instructions cover Linux. I tried `sudo apt install npm` but the result - and this may not be your fault - was:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by sr33** [comment]
Were you trying to install node & npm? 

If so you can download it [here](https://nodejs.org/en/).
If you prefer a package manager, follow these [instructions](https://askubuntu.com/a/1092849)


Don't forget to update your npm after installing node.

`npm install npm@latest -g`
